#!/usr/bin/env bash
# Firstly, to configure Nginx so its HTTP response can include a custom header (on web-01 & web-02)
# Secondly, the name of the custom HTTP header has to be X-Served-By
# Thirdly, the value of the custom HTTP header should be the hostname of the server Nginx is running on
sudo apt-get update
sudo apt-get -y install nginx
# To configure firewall to allow request through port 80
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html
# To also change the permissions to allow us easily create files in this directory
sudo chmod -R 755 /var/www
# To create the index page
echo 'Hello, World!' |sudo tee  /var/www/html/index.html
# To create webpage for error 404
echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html
# Then this is the code to configure redirect for a single page(/redirect_me) and also add header to display hostname
string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default
# This code is for configuring redirect for 404 error page
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default
# Finaly, to restart the web server after updating the settings
sudo service nginx restart
