#!/usr/bin/env bash
# First, to create a script that will install and also configure HAProxy on lb-01 server
# Then configure HAProxy so it sends traffic to web-01 and also web-02 servers
# That will also distribute requests by using a roundrobin algorithm
# To be certain that HAProxy can also be managed through an init script
# To install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# simply edit config file
server_config=\
"
frontend  fisayo-frontend
        bind *:80
        mode http
        default_backend fisayo-backend
backend fisayo-backend
        balance roundrobin
        server 74068-web-01 54.197.206.225:80 check
        server 74068-web-02 100.26.57.47:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
# enabling haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
