#!/usr/bin/env bash
# write a Bash script that configures an Nginx server to listen on port 80.
# nginx like sport 80

apt-get update -y
apt-get install -y nginx
sudo service nginx enable
sudo service nginx start

