#!/usr/bin/env bash
# write a Bash script that configures an Nginx server to listen on port 80. 
cat /etc/nginx/sites-available/default > /etc/nginx/sites-enabled/default
sudo service nginx restart
rm /run/nginx.pid
